[package]
name = "wutag_ipc"
version = "0.1.0"
authors = ["wojciechkepka <wojtek.kepka@protonmail.com>"]
edition = "2021"

[dependencies]
wutag_core = { path = "../wutag_core" }

interprocess = "1"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_cbor = "0.11"
thiserror = "1"
