name: master

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "*.md"
      - "LICENSE"
    branches:
      - master
  pull_request:
    paths-ignore:
      - "*.md"
      - "LICENSE"
    branches:
      - master
      - ci

env:
  CARGO_TERM_COLOR: always

jobs:
  codestyle:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Rust
        uses: hecrj/setup-rust-action@v1
        with:
          components: rustfmt
          rust-version: stable
      - uses: actions/checkout@v1
      - run: cargo fmt --all -- --check

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Rust
        uses: hecrj/setup-rust-action@v1
        with:
          components: clippy
      - uses: actions/checkout@v1
      - run: cargo clippy --all-targets -- -D clippy::all

  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Rust
        uses: hecrj/setup-rust-action@v1
      - uses: actions/checkout@master
      - run: cargo check --all

  test:
    needs: [codestyle, lint, compile]
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
      - name: Checkout
        uses: actions/checkout@v1
      - name: Test
        run: cargo test
